JetTurnonBarrel_SC8:
  version: V38nano
  sample: TT
  match_test_to_ref: True
  reference_object:
    object: "GenJetAK8"
    x_arg: "pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1puppiJetSC8:default:barrel: "pt"
  thresholds: [50] #, 100]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, barrel)"
  binning:
    min: 0
    max: 500
    step: 10

JetTurnonEndcap_SC8:
  version: V38nano
  sample: TT
  match_test_to_ref: True
  reference_object:
    object: "GenJetAK8"
    x_arg: "pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1puppiJetSC8:default:endcap: "pt"
  thresholds: [50] #, 100]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, endcap)"
  binning:
    min: 0
    max: 500
    step: 10
