JetMatching_Eta_Pt100ToInf:
  sample: TT
  version: V38nano
  match_test_to_ref: True
  reference_object:
    object: "GenJet"
    x_arg: "eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 100"
      object:
        - "abs({eta}) < 5"
  test_objects:
    L1puppiJetSC4:default: "eta"
    L1caloJet:default: "eta"
    L1TrackJet:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (Gen. $p_{T}$ > 100 GeV)"
  binning:
    min: -5
    max: 5
    step: 0.25

JetMatching_SC4SC8_Eta_Pt100ToInf:
  sample: TT
  version: V38nano
  match_test_to_ref: True
  reference_object:
    object: "GenJet"
    x_arg: "eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 100"
      object:
        - "abs({eta}) < 5"
  test_objects:
    L1puppiJetSC4:default: "eta"
    L1puppiJetSC8:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (Gen. $p_{T}$ > 100 GeV)"
  binning:
    min: -5
    max: 5
    step: 0.25

JetMatching_Eta_Pt40To100:
  sample: TT
  version: V38nano
  match_test_to_ref: True
  reference_object:
    object: "GenJet"
    x_arg: "eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 40"
        - "{pt} < 100"
      object:
        - "abs({eta}) < 5"
  test_objects:
    L1puppiJetSC4:default: "eta"
    L1caloJet:default: "eta"
    L1TrackJet:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (40 < Gen. $p_{T}$ < 100 GeV)"
  binning:
    min: -5
    max: 5
    step: 0.25
