PhotonsMatching_Eta_Pt40toInf:
  sample: Hgg
  version: V38nano
  match_test_to_ref: True
  reference_object:
    object: "GenPart"
    x_arg: "eta"
    label: "Gen Photons"
    cuts:
      event:
        - "(({statusFlags}>>7)&1) == 1"
        - "abs({pdgId}) == 22"
        - "{pt} > 40"
      object:
        - "abs({eta}) < 3.0"
  test_objects:
    L1tkPhoton:Iso_ptcut: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (Gen. $p_T > 40$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2

ElectronsMatching_Eta_Pt40toInf:
  sample: DYLL_M50
  version: V38nano
  match_test_to_ref: True
  reference_object:
    object: "GenPart"
    x_arg: "eta"
    label: "Gen Electrons"
    cuts:
      event:
        - "(({statusFlags}>>7)&1) == 1"
        - "abs({pdgId}) == 11"
        - "{pt} > 40"
      object:
        - "abs({eta}) < 3.0"
  test_objects:
    L1EG:default_ptcut: "eta"
    L1tkElectron:NoIso_ptcut: "eta"
    L1tkElectron:Iso_ptcut: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (Gen. $p_T > 40$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2
