PhotonEfficiency:
  sample: Hgg
  version: V38nano
  match_test_to_ref: True
  reference_object:
    object: "GenPart"
    x_arg: "pt"
    label: "Gen Photons"
    cuts:
      event:
        - "(({statusFlags}>>7)&1) == 1"
        - "abs({pdgId}) == 22"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1tkPhoton:Iso_ptcut: "pt"
  xlabel: "Gen. $p_{T}$ (GeV)"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 100
    step: 3

PhotonEfficiencyBarrel:
  sample: Hgg
  version: V38nano
  match_test_to_ref: True
  reference_object:
    object: "GenPart"
    x_arg: "pt"
    label: "Gen Photons"
    cuts:
      event:
        - "(({statusFlags}>>7)&1) == 1"
        - "abs({pdgId}) == 22"
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1tkPhoton:Iso_ptcut: "pt"
  xlabel: "Gen. $p_{T}$ (GeV)"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 100
    step: 3

PhotonEfficiencyEndcap:
  sample: Hgg
  version: V38nano
  match_test_to_ref: True
  reference_object:
    object: "GenPart"
    x_arg: "pt"
    label: "Gen Photons"
    cuts:
      event:
        - "(({statusFlags}>>7)&1) == 1"
        - "abs({pdgId}) == 22"
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1tkPhoton:Iso_ptcut: "pt"
  xlabel: "Gen. $p_{T}$ (GeV)"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 100
    step: 3
