TauMatching_Eta_Pt40To100:
  sample: VBFHToTauTau
  version: V38nano
  match_test_to_ref: True
  reference_object: 
    object: "GenVisTau"
    x_arg: "eta"
    label: "Gen Taus"
    cuts:
      event:
        - "{pt} > 40"
        - "{pt} < 100"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1nnPuppiTau:default: "eta"
    #L1hpsTau:default: "eta"
    L1caloTau:default: "eta"
    #L1nnCaloTau:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (40 < $p_{T}$ < 100 GeV)"
  binning:
    min: -3.0
    max: 3.0
    step: 0.2

TauMatching_Eta_Pt25ToInf:
  sample: VBFHToTauTau
  version: V38nano
  match_test_to_ref: True
  reference_object: 
    object: "GenVisTau"
    x_arg: "eta"
    label: "Gen Taus"
    cuts:
      event:
        - "{pt} > 25"
      object:
        - "abs({eta}) < 5"
  test_objects:
    L1nnPuppiTau:default: "eta"
    #L1hpsTau:default: "eta"
    L1caloTau:default: "eta"
    #L1nnCaloTau:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (Gen. $p_T$ > 25 GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2

TauMatching_Calo_Eta_Pt40To100:
  sample: VBFHToTauTau
  version: V38nano
  match_test_to_ref: True
  reference_object:
    object: "GenVisTau"
    x_arg: "eta"
    label: "Gen Taus"
    cuts:
      event:
        - "{pt} > 40"
        - "{pt} < 100"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1caloTau:default: "eta"
    L1nnCaloTau:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (40 < $p_{T}$ < 100 GeV)"
  binning:
    min: -3.0
    max: 3.0
    step: 0.2

TauMatching_Calo_Eta_Pt25ToInf:
  sample: VBFHToTauTau
  version: V38nano
  match_test_to_ref: True
  reference_object:
    object: "GenVisTau"
    x_arg: "eta"
    label: "Gen Taus"
    cuts:
      event:
        - "{pt} > 25"
      object:
        - "abs({eta}) < 5"
  test_objects:
    L1caloTau:default: "eta"
    L1nnCaloTau:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (Gen. $p_T$ > 25 GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2
