JetTurnonBarrelExt:
  version: V49nano_AR25_VtxFindOff
  sample: TT
  match_test_to_ref: True
  reference_object:
    object: "GenJet"
    x_arg: "pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1puppiExtJetSC4:default:barrel: "pt"
  thresholds: [50, 100]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, barrel)"
  binning:
    min: 0
    max: 500
    step: 10

JetTurnonEndcapExt:
  version: V49nano_AR25_VtxFindOff
  sample: TT
  match_test_to_ref: True
  reference_object:
    object: "GenJet"
    x_arg: "pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1puppiExtJetSC4:default:endcap: "pt"
  thresholds: [50, 100]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, endcap)"
  binning:
    min: 0
    max: 500
    step: 10

JetTurnonForwardHGCExt:
  version: V49nano_AR25_VtxFindOff
  sample: TT
  match_test_to_ref: True
  reference_object:
    object: "GenJet"
    x_arg: "pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 2.4"
      object:
        - "abs({eta}) < 3.0"
  test_objects:
    L1puppiExtJetSC4:default:forwardHGC: "pt"
  thresholds: [50, 100, 175]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, forwardHGC)"
  binning:
    min: 0
    max: 500
    step: 10

JetTurnonForwardHFExt:
  version: V49nano_AR25_VtxFindOff
  sample: TT
  match_test_to_ref: True
  reference_object:
    object: "GenJet"
    x_arg: "pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 3.0"
      object:
        - "abs({eta}) < 5.0"
  test_objects:
    L1puppiExtJetSC4:default:forwardHF: "pt"
  thresholds: [50, 100, 175]
  scalings:
    method: "naive"
    threshold: 0.60
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, forwardHF)"
  binning:
    min: 0
    max: 500
    step: 10
