MuonRates:
  sample: MinBias
  version: V38nano_DT12x
  test_objects:
    - L1gmtMuon:default
    - L1gmtTkMuon:VLoose
    - L1gmtTkMuon:lowpt_id
    - L1gmtTkMuon:default
    # - L1gmtTkMuon:Medium
    # - L1gmtTkMuon:Tight
  binning:
    min: 0
    max: 75
    step: 3
