# Purity_ElectronsBarrel:
#   sample: DYLL_M50
#   version: V44nano_GT
#   match_test_to_ref: True
#   reference_object:
#     object: "L1GTtkElectron"
#     x_arg: "pt"
#     label: "L1GTtkElectron"
#     cuts:
#       event:
#         - "{eleId} == 1"
#         - "abs({eta}) < 1.5"
#       object:
#         - "abs({eta}) < 2.4"
#   test_objects:
#     GenPart:electron: "pt"
#     L1EG:default: "pt"
#     # L1GTtkElectron:NoIso: "pt"
#     # L1GTtkElectron:NoIsoNoLowPtID: "pt"
#     # L1GTtkElectron:Iso: "pt"
#   xlabel: "L1 TkEle. $p_T$ (GeV)"
#   ylabel: "Matching Efficiency (Barrel)"
#   binning:
#     min: 0
#     max: 100
#     step: 3

Purity_ElectronsEndcap:
  sample: DYLL_M50
  version: V44nano_GT
  match_test_to_ref: True
  reference_object:
    object: "L1GTtkElectron"
    x_arg: "pt"
    label: "L1GTtkElectron"
    cuts:
      event:
        - "{eleId} == 1"
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    GenPart:electron: "pt"
    L1EG:default: "pt"
    # L1GTtkElectron:NoIso: "pt"
    # L1GTtkElectron:NoIsoNoLowPtID: "pt"
    # L1GTtkElectron:Iso: "pt"
  xlabel: "L1 TkEle. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  binning:
    min: 0
    max: 100
    step: 3
