L1caloJet:
  match_dR: 0.3
  label: "Calo Jet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
  cuts:
    inclusive:
      - "abs({eta}) < 7"
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 2.4"
    default_ptcut:
      label: "Calo Jet (L1 $p_{T}$ > 182 GeV)"
      cuts:
        inclusive:
          - "abs({eta}) < 2.4"
        barrel:
          - "{pt} > 215"
        endcap:
          - "{pt} > 148"

L1puppiJetSC4:
  match_dR: 0.35
  label: "Seeded Cone PuppiJet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 2.4"
    default_ptcut:
      label: "Seeded Cone PuppiJet (L1 $p_{T}$ > 143 GeV)"
      cuts:
        inclusive:
          - "abs({eta}) < 2.4"
        barrel:
          - "{pt} > 164"
        endcap:
          - "{pt} > 121"

L1TrackJet:
  match_dR: 0.4
  label: "Tracker Jet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 2.4"
    default_ptcut:
      label: "Tracker Jet (L1 $p_{T}$ > 114 GeV)"
      cuts:
        inclusive:
          - "abs({eta}) < 2.4"
        barrel:
          - "{pt} > 135"
        endcap:
          - "{pt} > 92"

L1puppiJetSC8:
  match_dR: 0.35
  label: "Seeded Cone PuppiJet 8"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 2.4"
    default_ptcut:
       cuts:
         inclusive:
          - "abs({eta}) < 2.4"
          - "{pt} > 140"
