L1nnPuppiTau:
  label: "NN Tau"
  match_dR: 0.1
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 2.5"
          # - "{passLooseNN}==1"
          # Current IB (22 Feb recipe) does not have updated WP, so cut on NN score rather than checking passLooseNN
          - "{chargedIso} > 0.22"
    default_ptcut:
      label: "NN Tau (L1 $p_{T}$ > 35 GeV)"
      cuts:
        inclusive:
          - "abs({eta}) < 2.5"
          - "{chargedIso} > 0.22"
          - "{pt} > 38"
        # barrel:
        #  - "{pt} > 38"
        #endcap:
        #  - "{pt} > 31"  

L1hpsTau:
  label: "HPS Tau"
  match_dR: 0.1
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 2.5"

L1caloTau:
  label: "Calo Tau"
  match_dR: 0.3
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 2.5"
    default_ptcut:
      label: "Calo Tau (L1 $p_{T}$ > 84 GeV)"
      cuts:
        inclusive:
          - "abs({eta}) < 2.5"
        barrel:
          - "{pt} > 97"
        endcap:
          - "{pt} > 78"
  PtGe20:
    label: "Calo Tau, pt > 20"
    cuts:
      inclusive:
        - "abs({eta}) < 2.4"
        - "{pt} > 20"

L1nnCaloTau:
  label: "NN Calo Tau"
  match_dR: 0.3
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 2.5"
          - "{hwQual}==3"
    default_ptcut:
      label: "NN Calo Tau (L1 $p_{T}$ > 80 GeV)"
      cuts:
        inclusive:
          - "abs({eta}) < 2.5"
          - "{hwQual}==3"
        barrel:
          - "{pt} > 90"
        endcap:
          - "{pt} > 84"
