JetSC8Rates:
  sample: MinBias
  version: V49nano_151pre1
  test_objects:
    - L1puppiJetSC4:default
    - L1puppiJetSC8:default
  binning:
    min: 40
    max: 420
    step: 20


JetSC8Rates_byRegion:
  sample: MinBias
  version: V49nano_151pre1
  test_objects:
    # - L1puppiJetSC4:default
    - L1puppiJetSC8:default
    - L1puppiJetSC8:default:barrel
    - L1puppiJetSC8:default:endcap
    - L1puppiJetSC8:default:forwardHGC
    - L1puppiJetSC8:default:forwardHF
  binning:
    min: 40
    max: 420
    step: 20
