TauRates:
  sample: MinBias
  version: V38nano
  test_objects:
    # - L1caloTau:default
    - L1nnPuppiTau:default
    - L1caloTau:default
    # - L1hpsTau:default
    # - L1caloTau:default
    # - L1nnCaloTau:default
  binning:
    min: 10
    max: 155
    step: 5

TauRatesCalo:
  sample: MinBias
  version: V38nano
  test_objects:
    # - L1nnPuppiTau:default
    # - L1hpsTau:default
    - L1nnCaloTau:default
    - L1caloTau:default
    # - L1nnCaloTau:default
  binning:
    min: 10
    max: 155
    step: 5
