JetMatching_Eta_Pt30ToInf_genGJets:
  sample: TT
  version: V49nano_AR25
  match_test_to_ref: True
  reference_object:
    object: "GenJet"
    x_arg: "eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 30"
        - "{partonFlavour} == 21"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1puppiJetSC4NG:gjetnn: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>30 GeV)"
  binning:
    min: -2.4
    max: 2.4
    step: 0.25

JetMatching_Eta_Pt30ToInf_genNotGJets:
  sample: TT
  version: V49nano_AR25
  match_test_to_ref: True
  reference_object:
    object: "GenJet"
    x_arg: "eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 30"
        - "{partonFlavour} != 21"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1puppiJetSC4NG:gjetnn: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>30 GeV)"
  binning:
    min: -2.4
    max: 2.4
    step: 0.25

JetMatching_Pt_Pt30ToInf_genGJets:
  sample: TT
  version: V49nano_AR25
  match_test_to_ref: True
  reference_object:
    object: "GenJet"
    x_arg: "pt"
    label: "Gen Jets"
    cuts:
      event:
        - "{partonFlavour} == 21"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1puppiJetSC4NG:gjetnn: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency"
  binning:
    min: 30
    max: 200
    step: 10

JetMatching_Pt_Pt30ToInf_genNotGJets:
  sample: TT
  version: V49nano_AR25
  match_test_to_ref: True
  reference_object:
    object: "GenJet"
    x_arg: "pt"
    label: "Gen Jets"
    cuts:
      event:
        - "{partonFlavour} != 21"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1puppiJetSC4NG:gjetnn: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency"
  binning:
    min: 30
    max: 200
    step: 10
