# Purity_ElectronsBarrel:
#   sample: DYLL_M50
#   version: V44nano
#   match_test_to_ref: True
#   reference_object:
#     L1tkElectron:reference:barrel: "pt"
#   test_objects:
#     GenPart:electron: "pt"
#     L1EG:default: "pt"
#     # L1tkElectron:NoIso: "pt"
#     # L1tkElectron:NoIsoNoLowPtID: "pt"
#     # L1tkElectron:Iso: "pt"
#   xlabel: "L1 TkEle. $p_T$ (GeV)"
#   ylabel: "Matching Efficiency (Barrel)"
#   binning:
#     min: 0
#     max: 100
#     step: 3

Purity_ElectronsEndcap:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  reference_object:
    L1tkElectron:reference_endcap: "pt"
  test_objects:
    GenPart:electron: "pt"
    L1EG:default: "pt"
    # L1tkElectron:NoIso: "pt"
    # L1tkElectron:NoIsoNoLowPtID: "pt"
    # L1tkElectron:Iso: "pt"
  xlabel: "L1 TkEle. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  binning:
    min: 0
    max: 100
    step: 3
