### SC8 wide cone jet seeds
L1_SinglePfJet8:
  cross_masks: []
  leg1:
    threshold_cut: offline_pt >= 230.0
    obj: L1puppiJetSC8:default

# ### SC8 wide cone jet seeds with mass cut
# L1_SinglePfJet8Mass30:
#   cross_masks: []
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass30

# L1_SinglePfJet8Mass29:
#   cross_masks: []
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass29

# L1_SinglePfJet8Mass28:
#   cross_masks: []
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass28

# L1_SinglePfJet8Mass27p5:
#   cross_masks: []
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass27p5

L1_SinglePfJet8Mass27:
  cross_masks: []
  leg1:
    threshold_cut: pt >= 0
    obj: L1puppiJetSC8:mass27

# L1_SinglePfJet8Mass26:
#   cross_masks: []
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass26

# L1_SinglePfJet8Mass25:
#   cross_masks: []
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass25

# L1_SinglePfJet8Mass20:
#   cross_masks: []
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass20

# L1_SinglePfJet8Mass15:
#   cross_masks: []
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass15

# L1_SinglePfJet8Mass10:
#   cross_masks: []
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass10

# L1_SinglePfJet8Mass5:
#   cross_masks: []
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass5

### Double wide jet mass
L1_DoublePFJet8_dEtaMax:
  cross_masks:
    - abs(leg2.eta-leg1.eta) < 1.6
  leg1:
    threshold_cut: leg1.offline_pt >= 200.0
    obj: L1puppiJetSC8:default
  leg2:
    threshold_cut: leg2.offline_pt >= 200.0
    obj: L1puppiJetSC8:default

# L1_DoublePFJet8_dEtaMaxMass30:
#   cross_masks:
#     - abs(leg2.eta-leg1.eta) < 1.6
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass30
#   leg2:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass30

# L1_DoublePFJet8_dEtaMaxMass25:
#   cross_masks:
#     - abs(leg2.eta-leg1.eta) < 1.6
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass25
#   leg2:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass25

# L1_DoublePFJet8_dEtaMaxMass20:
#   cross_masks:
#     - abs(leg2.eta-leg1.eta) < 1.6
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass20
#   leg2:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass20

L1_DoublePFJet8_dEtaMaxMass19:
  cross_masks:
    - abs(leg2.eta-leg1.eta) < 1.6
  leg1:
    threshold_cut: pt >= 0
    obj: L1puppiJetSC8:mass19
  leg2:
    threshold_cut: pt >= 0
    obj: L1puppiJetSC8:mass19

# L1_DoublePFJet8_dEtaMaxMass18p5:
#   cross_masks:
#     - abs(leg2.eta-leg1.eta) < 1.6
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass18p5
#   leg2:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass18p5

# L1_DoublePFJet8_dEtaMaxMass18:
#   cross_masks:
#     - abs(leg2.eta-leg1.eta) < 1.6
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass18
#   leg2:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass18

# L1_DoublePFJet8_dEtaMaxMass17:
#   cross_masks:
#     - abs(leg2.eta-leg1.eta) < 1.6
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass17
#   leg2:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass17

# L1_DoublePFJet8_dEtaMaxMass16:
#   cross_masks:
#     - abs(leg2.eta-leg1.eta) < 1.6
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass16
#   leg2:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass16

# L1_DoublePFJet8_dEtaMaxMass15:
#   cross_masks:
#     - abs(leg2.eta-leg1.eta) < 1.6
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass15
#   leg2:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass15

# L1_DoublePFJet8_dEtaMaxMass10:
#   cross_masks:
#     - abs(leg2.eta-leg1.eta) < 1.6
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass10
#   leg2:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass10

# L1_DoublePFJet8_dEtaMaxMass5:
#   cross_masks:
#     - abs(leg2.eta-leg1.eta) < 1.6
#   leg1:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass5
#   leg2:
#     threshold_cut: pt >= 0
#     obj: L1puppiJetSC8:mass5


# B Jet Seeds
L1_PFHTT_QuadJet_BTagNNScore:
  cross_masks:
    - (leg2.btagScore + leg3.btagScore + leg4.btagScore + leg5.btagScore) > 2.20
  leg1:
    threshold_cut: offline_pt >= 299.0
    obj: L1puppiJetSC4sums:HT
  leg2:
    threshold_cut: pt >= 25
    obj: L1puppiExtJetSC4:default
  leg3:
    threshold_cut: pt >= 25
    obj: L1puppiExtJetSC4:default
  leg4:
    threshold_cut: pt >= 25
    obj: L1puppiExtJetSC4:default
  leg5:
    threshold_cut: pt >= 25
    obj: L1puppiExtJetSC4:default

L1_PFHTT_QuadJetNG_BTagNNScore:
  cross_masks:
    - (leg2.bTagScore + leg3.bTagScore + leg4.bTagScore + leg5.bTagScore) > 0
  leg1:
    threshold_cut: offline_pt >= 299.0
    obj: L1puppiJetSC4sums:HT
  leg2:
    threshold_cut: pt >= 25
    obj: L1puppiJetSC4NG:default
  leg3:
    threshold_cut: pt >= 25
    obj: L1puppiJetSC4NG:default
  leg4:
    threshold_cut: pt >= 25
    obj: L1puppiJetSC4NG:default
  leg5:
    threshold_cut: pt >= 25
    obj: L1puppiJetSC4NG:default
