L1caloJet:
  match_dR: 0.3
  label: "Calo Jet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
    forward: [2.4, 5]
  cuts:
    inclusive:
      - "abs({eta}) < 7"
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 7"

L1puppiExtJetSC4:
  match_dR: 0.35
  label: "Seeded Cone Extended PuppiJet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
    forward: [2.4, 5]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 5"
    bjetnn:
      label: "SC Extended PuppiJet, BtagScore > 0.71"
      cuts:
        inclusive:
          - "abs({eta}) < 2.4"
          - "{btagScore} > 0.71"

L1puppiJetHisto:
  match_dR: 0.3
  label: "Histogrammed PuppiJet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
    forward: [2.4, 5]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 7"

L1puppiJetSC4:
  match_dR: 0.35
  label: "Seeded Cone PuppiJet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
    forward: [2.4, 5]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 7"

L1puppiJetSC8:
  match_dR: 0.35
  label: "Seeded Cone PuppiJet 8"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
    forward: [2.4, 5]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 7"

L1TrackJet:
  match_dR: 0.4
  label: "Tracker Jet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 7"


